# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PersonalDiary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'bbetsey2022', :path => '../bbetsey2022/'
  # Pods for PersonalDiary

end
